apiVersion: v1
kind: Secret
metadata:
  name: infera-secrets
type: Opaque
stringData:
  OPENROUTER_API_KEY: ""
  POSTGRES_USER: "infera"
  POSTGRES_PASSWORD: "infera"
  CLICKHOUSE_USER: "infera"
  CLICKHOUSE_PASSWORD: "infera"
